Prefer snprintf over sprintf in OpenGL
love2d/love pull request #1883
Opened 2022-12-26 23:01 UTC by devenvexe

Silences warnings about deprecated sprintf under Xcode 14

2022-12-26 23:11 UTC, slime73 requested changes
love 11 uses VS2013 on Windows for official builds, which doesn't support snprintf. love 12 uses VS2019 (or later) which does, so I think this change will be good if it's based on the `12.0-development` branch instead of `main`.

2022-12-27 01:20 UTC, devenvexe commented
I'll move the PR. Thanks.

2022-12-27 01:48 UTC, MikuAuahDark commented
To workaround MSVC 2013, I use something like this 75a3e5db015c05699d0e9f2314801ace505fbd48

2022-12-27 01:52 UTC, slime73 commented
I think I'd rather have the clean snprintf change in 12.0 rather than some #ifdefs.

2022-12-27 01:52 UTC, devenvexe commented
That's cool - and my previous #ifdef won't work of course as I misremembered what is visible when during preprocessor and compilation phases.

2022-12-27 01:53 UTC, devenvexe commented
Closing in favor of opening against 12

2022-12-27 01:53 UTC, closed without merging