Work around an issue with github builders
love2d/love pull request #2121
Opened 2024-11-29 13:41 UTC by learn-more

2024-11-29 15:21 UTC, MikuAuahDark requested changes

2024-11-29 15:21 UTC, MikuAuahDark commented on .github/workflows/main.yml
> +      run: cmake -Bbuild -Smegasource -T v143 -A ${{ matrix.platform }} --install-prefix %CD%\install -DCMAKE_PDB_OUTPUT_DIRECTORY=%CD%\pdb -DCMAKE_SYSTEM_VERSION=10.0.26100.0 ${{ steps.vars.outputs.
Specifying Windows SDK version using `CMAKE_SYSTEM_VERSION` is deprecated. See https://cmake.org/cmake/help/latest/policy/CMP0149.html.

```suggestion
      run: cmake -Bbuild -Smegasource -T v143 -A ${{ matrix.platform }},version=10.0.26100.0 --install-prefix %CD%\install -DCMAKE_PDB_OUTPUT_DIRECTORY=%CD%\pdb ${{ steps.vars.outputs.moredef }}
```

2024-11-30 16:09 UTC, slime73 commented
Are the arm64 failures in this PR's CI related to the change? I wonder what's needed to fix them

2024-12-01 05:57 UTC, MikuAuahDark approved these changes

2024-12-01 05:58 UTC, MikuAuahDark commented
> Are the arm64 failures in this PR's CI related to the change?

No. It's caused by ARM64 misdetection in megasource. Fixed in love2d/megasource@afe097c.

2024-12-01 07:04 UTC, merged

2024-12-01 13:51 UTC, slime73 commented
Thanks!